### ISSUE TITLE
Vim Autocdls turns CmdAlias off. 

### ISSUE THREAD

**Issue by ReneFroger** [b4b4r07/vim-autocdls#1]
Thanks for sharing this awesome plugin with us! But are you aware this turns off the CmdAlias feature of Vim? 

For example

```
  autocmd VimEnter * call CmdAlias('gen', 'e C:\Dropbox\Vim\.vim\setup\general.vim')
```

Then `:gen` will not work anymore when this plugin is installed.

**Comment by babarot** [comment]
Thank you for your bug report. However, I'm not going to fix this bug baceuse it is not critical for those who do not use the `CmdAlias` plugin. If you want to fix this bug, please **pull request**.

Thank you.
